export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  popular?: boolean;
}

export interface Restaurant {
  slug: string;
  name: string;
  tagline: string;
  cuisine: string[];
  rating: number;
  reviewCount: number;
  deliveryTime: string;
  deliveryFee: number;
  minOrder: number;
  address: string;
  area: string;
  image: string;
  logo: string;
  featured?: boolean;
  phone: string;
  menu: MenuItem[];
}

export const restaurants: Restaurant[] = [
  {
    slug: "the-yellow-chilli",
    name: "The Yellow Chilli",
    tagline: "Elevated Nigerian classics with a contemporary finish.",
    cuisine: ["Nigerian", "Contemporary"],
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: "25-35 min",
    deliveryFee: 1200,
    minOrder: 3000,
    address: "35 Bishop Oluwole Street, Victoria Island, Lagos",
    area: "Victoria Island, Lagos",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80",
    logo: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=100&q=80",
    featured: true,
    phone: "+234 801 234 5678",
    menu: [
      {
        id: "jollof-rice-chicken",
        name: "Jollof Rice & Chicken",
        description:
          "Smoky party-style jollof rice served with grilled chicken thigh and coleslaw.",
        price: 4500,
        image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80",
        category: "Rice Dishes",
        popular: true,
      },
      {
        id: "fried-rice-turkey",
        name: "Fried Rice & Turkey",
        description:
          "Nigerian fried rice with mixed vegetables, prawns, and a fried turkey drumstick.",
        price: 5200,
        image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80",
        category: "Rice Dishes",
      },
      {
        id: "native-jollof",
        name: "Native Jollof",
        description:
          "Traditional palm oil jollof with smoked fish, locust beans and assorted meat.",
        price: 5800,
        image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
        category: "Rice Dishes",
      },
      {
        id: "egusi-pounded-yam",
        name: "Egusi Soup & Pounded Yam",
        description:
          "Rich melon seed soup with assorted meat, stockfish, and smooth pounded yam.",
        price: 4800,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80",
        category: "Soups & Swallows",
        popular: true,
      },
      {
        id: "efo-riro-amala",
        name: "Efo Riro & Amala",
        description: "Hearty spinach stew with assorted meat and soft amala.",
        price: 4200,
        image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80",
        category: "Soups & Swallows",
      },
      {
        id: "moi-moi",
        name: "Moi Moi",
        description: "Steamed bean pudding with eggs and corned beef.",
        price: 1200,
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80",
        category: "Sides & Drinks",
      },
      {
        id: "chapman",
        name: "Chapman",
        description:
          "Classic Nigerian cocktail with Fanta, Sprite, grenadine and bitters.",
        price: 1500,
        image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",
        category: "Sides & Drinks",
      },
    ],
  },
  {
    slug: "yahuza-suya",
    name: "Yahuza Suya Spot",
    tagline: "Legendary northern suya and grills, hot off the charcoal.",
    cuisine: ["Nigerian", "Grills"],
    rating: 4.6,
    reviewCount: 218,
    deliveryTime: "20-30 min",
    deliveryFee: 800,
    minOrder: 2000,
    address: "24 Adetokunbo Ademola Crescent, Wuse 2, Abuja",
    area: "Wuse 2, Abuja",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
    logo: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=100&q=80",
    featured: true,
    phone: "+234 809 441 1020",
    menu: [
      {
        id: "beef-suya",
        name: "Beef Suya",
        description:
          "Classic spiced beef strips grilled over charcoal, served with onions and tomatoes.",
        price: 3200,
        image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=400&q=80",
        category: "Suya & Grills",
        popular: true,
      },
      {
        id: "chicken-suya",
        name: "Chicken Suya",
        description: "Marinated chicken thighs grilled with suya spice blend.",
        price: 3500,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
        category: "Suya & Grills",
      },
      {
        id: "ram-suya",
        name: "Ram Suya",
        description: "Tender ram meat seasoned and grilled to perfection.",
        price: 4000,
        image: "https://images.unsplash.com/photo-1558030006-450675393462?w=400&q=80",
        category: "Suya & Grills",
      },
      {
        id: "kilishi",
        name: "Kilishi",
        description: "Dried spiced beef jerky — Nigerian-style.",
        price: 2800,
        image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&q=80",
        category: "Suya & Grills",
      },
      {
        id: "grilled-plantain",
        name: "Grilled Plantain",
        description: "Sweet ripe plantain grilled with pepper sauce.",
        price: 800,
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80",
        category: "Sides",
      },
      {
        id: "yaji-mix",
        name: "Suya Spice Mix (take-home)",
        description: "Our signature yaji spice blend to take home.",
        price: 1500,
        image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
        category: "Sides",
      },
    ],
  },
  {
    slug: "mama-cass",
    name: "Mama Cass",
    tagline: "Comforting Nigerian meals for everyday cravings and family feasts.",
    cuisine: ["Nigerian", "Traditional"],
    rating: 4.7,
    reviewCount: 512,
    deliveryTime: "30-40 min",
    deliveryFee: 1000,
    minOrder: 2500,
    address: "62 Adeniran Ogunsanya Street, Surulere, Lagos",
    area: "Adeniran Ogunsanya, Surulere, Lagos",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
    logo: "https://images.unsplash.com/photo-1547592180-85f173990554?w=100&q=80",
    phone: "+234 807 332 1191",
    menu: [
      {
        id: "ofada-rice-sauce",
        name: "Ofada Rice & Sauce",
        description:
          "Local unpolished rice with spicy green pepper sauce and assorted meat.",
        price: 4000,
        image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
        category: "Soups & Swallows",
        popular: true,
      },
      {
        id: "banga-soup-starch",
        name: "Banga Soup & Starch",
        description: "Palm fruit soup with fresh fish and soft starch.",
        price: 4500,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80",
        category: "Soups & Swallows",
      },
      {
        id: "pepper-soup-goat",
        name: "Pepper Soup (Goat)",
        description: "Spicy goat meat pepper soup with utazi leaves.",
        price: 3800,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80",
        category: "Soups & Swallows",
      },
      {
        id: "coconut-rice",
        name: "Coconut Rice",
        description: "Fragrant coconut-infused rice with fried plantain and chicken.",
        price: 3500,
        image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80",
        category: "Rice Dishes",
      },
      {
        id: "jollof-spaghetti",
        name: "Jollof Spaghetti",
        description: "Nigerian-style pasta in rich tomato and pepper sauce.",
        price: 2800,
        image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80",
        category: "Rice Dishes",
      },
      {
        id: "puff-puff",
        name: "Puff Puff",
        description: "Golden fried dough balls — sweet and fluffy.",
        price: 1000,
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80",
        category: "Small Chops",
      },
      {
        id: "spring-rolls",
        name: "Spring Rolls (6 pcs)",
        description: "Crispy vegetable spring rolls with sweet chilli dip.",
        price: 1500,
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80",
        category: "Small Chops",
      },
    ],
  },
  {
    slug: "bukka-hut",
    name: "Bukka Hut",
    tagline: "Fast casual bukka favourites, dressed up for busy city days.",
    cuisine: ["Nigerian", "Fast Food", "Contemporary"],
    rating: 4.5,
    reviewCount: 289,
    deliveryTime: "25-35 min",
    deliveryFee: 1000,
    minOrder: 2500,
    address: "12 Admiralty Way, Lekki Phase 1, Lagos",
    area: "Lekki Phase 1, Lagos",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&q=80",
    logo: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=100&q=80",
    featured: true,
    phone: "+234 812 450 9982",
    menu: [
      {
        id: "amala-ewedu",
        name: "Amala & Ewedu",
        description: "Soft amala with silky ewedu, gbegiri and rich buka stew.",
        price: 3800,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80",
        category: "Classics",
        popular: true,
      },
      {
        id: "porridge-beans-plantain",
        name: "Porridge Beans & Plantain",
        description: "Creamy stewed beans served with ripe fried plantain slices.",
        price: 2500,
        image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
        category: "Classics",
      },
      {
        id: "suya-wrap",
        name: "Suya Wrap",
        description: "Spiced beef suya wrapped in warm flatbread with slaw and sauce.",
        price: 2800,
        image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&q=80",
        category: "Combos",
      },
      {
        id: "jollof-party-pack",
        name: "Jollof Party Pack",
        description: "Smoky jollof rice, beef, dodo and tangy coleslaw in one tray.",
        price: 4200,
        image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80",
        category: "Combos",
        popular: true,
      },
      {
        id: "yam-egg-sauce",
        name: "Yam & Egg Sauce",
        description: "Boiled yam cubes topped with peppery tomato egg sauce.",
        price: 2400,
        image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80",
        category: "Classics",
      },
      {
        id: "peppered-gizzard-bowl",
        name: "Peppered Gizzard Bowl",
        description: "Tender gizzard tossed in spicy sauce with onions and peppers.",
        price: 2200,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
        category: "Combos",
      },
    ],
  },
  {
    slug: "cafe-neo",
    name: "Café Neo",
    tagline: "Coffee, smoothies and light bites for workdays that need fuel.",
    cuisine: ["Café", "Light Bites"],
    rating: 4.4,
    reviewCount: 176,
    deliveryTime: "20-30 min",
    deliveryFee: 800,
    minOrder: 2000,
    address: "2 Idowu Taylor Street, Victoria Island, Lagos",
    area: "Victoria Island, Lagos",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80",
    logo: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=100&q=80",
    phone: "+234 813 500 4110",
    menu: [
      {
        id: "avocado-toast",
        name: "Avocado Toast",
        description: "Sourdough toast layered with smashed avocado, chili flakes and microgreens.",
        price: 3200,
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80",
        category: "All Day Breakfast",
        popular: true,
      },
      {
        id: "chicken-caesar-wrap",
        name: "Chicken Caesar Wrap",
        description: "Grilled chicken, romaine and parmesan rolled in a soft tortilla wrap.",
        price: 3800,
        image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&q=80",
        category: "Wraps & Sandwiches",
      },
      {
        id: "smoothie-bowl",
        name: "Smoothie Bowl",
        description: "Banana berry smoothie topped with granola, coconut and fresh fruit.",
        price: 2800,
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80",
        category: "All Day Breakfast",
      },
      {
        id: "fresh-juice",
        name: "Fresh Juice",
        description: "Cold-pressed orange, pineapple and ginger juice made to order.",
        price: 1500,
        image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",
        category: "Coffee & Drinks",
      },
      {
        id: "iced-latte",
        name: "Iced Vanilla Latte",
        description: "Espresso, milk and vanilla syrup poured over ice.",
        price: 2200,
        image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400&q=80",
        category: "Coffee & Drinks",
        popular: true,
      },
      {
        id: "turkey-club-sandwich",
        name: "Turkey Club Sandwich",
        description: "Triple-stacked sandwich with turkey, tomato, lettuce and herb mayo.",
        price: 3600,
        image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&q=80",
        category: "Wraps & Sandwiches",
      },
    ],
  },
  {
    slug: "nkoyo",
    name: "Nkoyo",
    tagline: "Refined Nigerian fine dining prepared with ceremonial detail.",
    cuisine: ["Nigerian", "Fine Dining"],
    rating: 4.9,
    reviewCount: 156,
    deliveryTime: "35-45 min",
    deliveryFee: 1500,
    minOrder: 5000,
    address: "1 Bathurst Street, Maitama, Abuja",
    area: "Maitama, Abuja",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80",
    logo: "https://images.unsplash.com/photo-1547592180-85f173990554?w=100&q=80",
    phone: "+234 810 660 8743",
    menu: [
      {
        id: "grilled-croaker-fish",
        name: "Grilled Croaker Fish",
        description: "Whole croaker grilled with ata rodo glaze, served with herbed potatoes.",
        price: 8500,
        image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80",
        category: "Signature Plates",
        popular: true,
      },
      {
        id: "peppered-snail",
        name: "Peppered Snail",
        description: "Tender snail tossed in glossy pepper sauce with bell peppers and onions.",
        price: 6200,
        image: "https://images.unsplash.com/photo-1558030006-450675393462?w=400&q=80",
        category: "Starters",
      },
      {
        id: "asun",
        name: "Asun",
        description: "Charred goat meat cubes finished with hot green pepper reduction.",
        price: 5500,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
        category: "Starters",
        popular: true,
      },
      {
        id: "seafood-okra",
        name: "Seafood Okra & Semovita",
        description: "Velvety okra soup with prawns and crab served beside soft semovita.",
        price: 7000,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80",
        category: "Signature Plates",
      },
      {
        id: "ofada-duck",
        name: "Ofada Rice & Duck Sauce",
        description: "Stone-ground ofada rice with smoked duck in rich green pepper sauce.",
        price: 7800,
        image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
        category: "Signature Plates",
      },
      {
        id: "zobo-spritz",
        name: "Zobo Spritz",
        description: "Sparkling hibiscus drink with citrus peel and cloves.",
        price: 1800,
        image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",
        category: "Beverages",
      },
    ],
  },
  {
    slug: "kilimanjaro",
    name: "Kilimanjaro",
    tagline: "Fast-food comfort, shawarma cravings and quick wins for hungry days.",
    cuisine: ["Fast Food", "Shawarma"],
    rating: 4.3,
    reviewCount: 198,
    deliveryTime: "15-25 min",
    deliveryFee: 600,
    minOrder: 1500,
    address: "31A Woji Road, GRA Phase 3, Port Harcourt",
    area: "GRA Phase 3, Port Harcourt",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80",
    logo: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=100&q=80",
    phone: "+234 815 900 2301",
    menu: [
      {
        id: "beef-shawarma",
        name: "Beef Shawarma",
        description: "Toasted shawarma wrap with spiced beef strips, cabbage and creamy sauce.",
        price: 2500,
        image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&q=80",
        category: "Shawarma & Wraps",
        popular: true,
      },
      {
        id: "chicken-shawarma",
        name: "Chicken Shawarma",
        description: "Classic shawarma stuffed with juicy chicken and crisp vegetables.",
        price: 2800,
        image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
        category: "Shawarma & Wraps",
      },
      {
        id: "shawarma-platter",
        name: "Shawarma Platter",
        description: "Sliced beef and chicken shawarma served over fries with garlic dip.",
        price: 5000,
        image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=400&q=80",
        category: "Combos",
      },
      {
        id: "loaded-fries",
        name: "Loaded Fries",
        description: "Crispy fries topped with suya beef, cheese sauce and scallions.",
        price: 1800,
        image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?w=400&q=80",
        category: "Combos",
      },
      {
        id: "zinger-burger",
        name: "Zinger Burger",
        description: "Spicy fried chicken burger with crunchy slaw and chili mayo.",
        price: 3000,
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
        category: "Fast Food",
        popular: true,
      },
      {
        id: "vanilla-milkshake",
        name: "Vanilla Milkshake",
        description: "Creamy vanilla shake blended with ice cream and fresh milk.",
        price: 1600,
        image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&q=80",
        category: "Drinks",
      },
    ],
  },
  {
    slug: "terra-kulture",
    name: "Terra Kulture",
    tagline: "Cultural dining with polished Nigerian plates and theatre-night energy.",
    cuisine: ["Nigerian", "Contemporary"],
    rating: 4.7,
    reviewCount: 231,
    deliveryTime: "30-40 min",
    deliveryFee: 1200,
    minOrder: 3500,
    address: "1376 Tiamiyu Savage Street, Victoria Island, Lagos",
    area: "Tiamiyu Savage, Victoria Island, Lagos",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
    logo: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=100&q=80",
    phone: "+234 802 776 4509",
    menu: [
      {
        id: "gizdodo",
        name: "Gizdodo",
        description: "Peppered gizzard tossed with sweet fried plantain cubes.",
        price: 3200,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
        category: "Starters",
        popular: true,
      },
      {
        id: "asun-terra",
        name: "Asun",
        description: "Smoky goat meat bites finished with green pepper and onions.",
        price: 4500,
        image: "https://images.unsplash.com/photo-1558030006-450675393462?w=400&q=80",
        category: "Starters",
      },
      {
        id: "catfish-pepper-soup",
        name: "Catfish Pepper Soup",
        description: "Fresh catfish in a fragrant pepper broth with scent leaves.",
        price: 4800,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80",
        category: "Signature Plates",
      },
      {
        id: "plantain-beans-porridge",
        name: "Plantain & Beans Porridge",
        description: "Soft beans and ripe plantain stewed together with smoked fish.",
        price: 3000,
        image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
        category: "Signature Plates",
      },
      {
        id: "seafood-jollof",
        name: "Seafood Jollof Rice",
        description: "Party jollof loaded with prawns, calamari and grilled fish.",
        price: 5600,
        image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80",
        category: "Signature Plates",
        popular: true,
      },
      {
        id: "hibiscus-fizz",
        name: "Hibiscus Fizz",
        description: "Sparkling zobo drink with citrus and a touch of ginger.",
        price: 1600,
        image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",
        category: "Beverages",
      },
    ],
  },
];

export const cuisineFilters = [
  "All",
  "Nigerian",
  "Grills",
  "Traditional",
  "Contemporary",
  "Fast Food",
  "Café",
  "Fine Dining",
  "Shawarma",
];

export const areaFilters = ["All Areas", "Lagos", "Abuja", "Port Harcourt"];

export function getRestaurantBySlug(slug: string) {
  return restaurants.find((restaurant) => restaurant.slug === slug);
}
